pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'UsbTouchpadAndroid'
include ':app'
include ':protocol'
project(':protocol').projectDir = new File(settingsDir, '../touchpad-protocol')
